/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Plan = IDL.Variant({
  'free' : IDL.Null,
  'monthly' : IDL.Null,
  'yearly' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TeamRole = IDL.Variant({
  'pitCrew' : IDL.Null,
  'director' : IDL.Null,
  'driver' : IDL.Null,
});
export const XPCoinType = IDL.Variant({
  'xp1' : IDL.Null,
  'xp5' : IDL.Null,
  'xp10' : IDL.Null,
  'xp20' : IDL.Null,
});
export const AIInput = IDL.Record({
  'backward' : IDL.Bool,
  'forward' : IDL.Bool,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const GroupType = IDL.Variant({
  'race' : IDL.Null,
  'tournament' : IDL.Null,
});
export const AIRaceResult = IDL.Record({
  'completionTime' : IDL.Opt(IDL.Nat),
  'bestTime' : IDL.Opt(IDL.Nat),
  'attempts' : IDL.Nat,
  'srProgression' : IDL.Opt(IDL.Nat),
  'trackId' : IDL.Text,
});
export const StoreItem = IDL.Record({
  'costInXP' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'srLevel' : IDL.Nat,
  'name' : IDL.Text,
  'skillRating' : IDL.Nat,
  'winRate' : IDL.Float64,
  'totalRaces' : IDL.Nat,
});
export const Time = IDL.Int;
export const DirectMessage = IDL.Record({
  'content' : IDL.Text,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});
export const TrackPosition = IDL.Nat16;
export const Position = IDL.Record({
  'checkpoint' : IDL.Nat8,
  'position' : TrackPosition,
});
export const F1RacingTrack = IDL.Record({
  'textureAsset' : IDL.Text,
  'pitLane' : IDL.Vec(Position),
  'checkpoints' : IDL.Vec(Position),
  'finishLine' : IDL.Vec(Position),
  'points' : IDL.Vec(Position),
});
export const Season = IDL.Nat8;
export const LeaderboardEntry = IDL.Record({
  'player' : IDL.Principal,
  'skill' : IDL.Nat,
});
export const StoreData = IDL.Record({
  'userXP' : IDL.Nat,
  'totalPurchased' : IDL.Nat,
  'ownedItems' : IDL.Vec(IDL.Text),
  'availableItems' : IDL.Vec(StoreItem),
});
export const GroupView = IDL.Record({
  'owner' : IDL.Principal,
  'maxCapacity' : IDL.Nat,
  'name' : IDL.Text,
  'memberCount' : IDL.Nat,
  'trackId' : IDL.Opt(IDL.Text),
  'groupType' : GroupType,
});
export const PlayerStats = IDL.Record({
  'totalTime' : IDL.Nat,
  'races' : IDL.Nat,
});
export const RaceStats = IDL.Record({
  'bestTime' : IDL.Nat,
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
});
export const Subscription = IDL.Record({
  'status' : IDL.Variant({
    'active' : IDL.Null,
    'canceled' : IDL.Null,
    'expired' : IDL.Null,
  }),
  'plan' : Plan,
  'expirationDate' : IDL.Opt(Time),
  'stripeSessionId' : IDL.Opt(IDL.Text),
  'startDate' : Time,
});
export const LapTime = IDL.Record({ 'lap' : IDL.Nat, 'time' : IDL.Int });
export const CarState = IDL.Record({
  'isRacing' : IDL.Bool,
  'direction' : IDL.Float64,
  'velocity' : IDL.Float64,
  'laps' : IDL.Nat,
  'lapTimes' : IDL.Vec(LapTime),
  'position' : Position,
});
export const StoreStatus = IDL.Record({
  'balance' : IDL.Nat,
  'ownedItems' : IDL.Vec(IDL.Text),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const TeamMember = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'role' : TeamRole,
});
export const TeamRoster = IDL.Record({
  'directors' : IDL.Vec(TeamMember),
  'pitCrew' : IDL.Vec(TeamMember),
  'drivers' : IDL.Vec(TeamMember),
});
export const Race = IDL.Record({ 'score' : IDL.Nat, 'driver' : IDL.Principal });
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activatePaidPlan' : IDL.Func([Plan, IDL.Text], [], []),
  'addFriend' : IDL.Func([IDL.Principal], [], []),
  'addRace' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelSubscription' : IDL.Func([], [], []),
  'changeRole' : IDL.Func([TeamRole], [], []),
  'collectXPCoin' : IDL.Func([XPCoinType, IDL.Text], [IDL.Nat], []),
  'completeAIRace' : IDL.Func([IDL.Text, AIInput], [IDL.Nat], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createGroup' : IDL.Func(
      [IDL.Text, GroupType, IDL.Nat, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'creditXP' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'finishRace' : IDL.Func([IDL.Text], [], []),
  'getAIDrivenRaceResults' : IDL.Func([], [IDL.Opt(AIRaceResult)], ['query']),
  'getAvailablePlans' : IDL.Func([], [IDL.Vec(Plan)], ['query']),
  'getAvailableStoreItems' : IDL.Func([], [IDL.Vec(StoreItem)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversationWithPeer' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DirectMessage)],
      ['query'],
    ),
  'getCurrentPlan' : IDL.Func([], [Plan], ['query']),
  'getF1RacingTrack' : IDL.Func([], [IDL.Opt(F1RacingTrack)], ['query']),
  'getFriendsLeaderboard' : IDL.Func(
      [Season],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getFullStoreData' : IDL.Func([], [StoreData], ['query']),
  'getGlobalLeaderboard' : IDL.Func(
      [Season],
      [IDL.Opt(IDL.Vec(LeaderboardEntry))],
      ['query'],
    ),
  'getGroupMembers' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Principal)], ['query']),
  'getGroups' : IDL.Func([], [IDL.Vec(GroupView)], ['query']),
  'getLeaderboardFriends' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getMyFriends' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getMyOwnedItems' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getMyPlayerStats' : IDL.Func([], [IDL.Opt(PlayerStats)], ['query']),
  'getMyRaceStats' : IDL.Func([], [IDL.Opt(RaceStats)], ['query']),
  'getMySubscription' : IDL.Func([], [Subscription], ['query']),
  'getPlanExpiration' : IDL.Func([], [IDL.Opt(Time)], ['query']),
  'getPlanPricing' : IDL.Func([Plan], [IDL.Nat], ['query']),
  'getPlayerStats' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PlayerStats)],
      ['query'],
    ),
  'getRaceCarStates' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Opt(CarState)))],
      ['query'],
    ),
  'getRacePositions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Opt(Position)))],
      ['query'],
    ),
  'getRaceStats' : IDL.Func([IDL.Principal], [IDL.Opt(RaceStats)], ['query']),
  'getStoreStatus' : IDL.Func([], [StoreStatus], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTeamRoster' : IDL.Func([], [TeamRoster], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'joinGroup' : IDL.Func([IDL.Text], [], []),
  'joinMatchmaking' : IDL.Func([], [], []),
  'joinRace' : IDL.Func([IDL.Text], [], []),
  'joinTeam' : IDL.Func([IDL.Text, TeamRole], [], []),
  'leaveGroup' : IDL.Func([IDL.Text], [], []),
  'leaveTeam' : IDL.Func([], [], []),
  'progressSRByAI' : IDL.Func([IDL.Nat], [], []),
  'purchaseItem' : IDL.Func([IDL.Text], [], []),
  'registerRaceResult' : IDL.Func([Race], [], []),
  'removeFriend' : IDL.Func([IDL.Principal], [], []),
  'resetSeason' : IDL.Func([Season], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendDirectMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'setF1RacingTrack' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(Position),
        IDL.Vec(Position),
        IDL.Vec(Position),
        IDL.Vec(Position),
      ],
      [],
      [],
    ),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'setWorldRaceRecord' : IDL.Func([IDL.Text, IDL.Int], [], []),
  'startAIRace' : IDL.Func([IDL.Text, AIInput], [], []),
  'startRace' : IDL.Func([IDL.Text], [], []),
  'startTournament' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCarState' : IDL.Func(
      [Position, IDL.Float64, IDL.Float64, IDL.Nat],
      [],
      [],
    ),
  'updateCurrentSeason' : IDL.Func([IDL.Nat], [], []),
  'updateLeaderboard' : IDL.Func([Season, IDL.Vec(LeaderboardEntry)], [], []),
  'updateRaceStats' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Plan = IDL.Variant({
    'free' : IDL.Null,
    'monthly' : IDL.Null,
    'yearly' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TeamRole = IDL.Variant({
    'pitCrew' : IDL.Null,
    'director' : IDL.Null,
    'driver' : IDL.Null,
  });
  const XPCoinType = IDL.Variant({
    'xp1' : IDL.Null,
    'xp5' : IDL.Null,
    'xp10' : IDL.Null,
    'xp20' : IDL.Null,
  });
  const AIInput = IDL.Record({ 'backward' : IDL.Bool, 'forward' : IDL.Bool });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const GroupType = IDL.Variant({ 'race' : IDL.Null, 'tournament' : IDL.Null });
  const AIRaceResult = IDL.Record({
    'completionTime' : IDL.Opt(IDL.Nat),
    'bestTime' : IDL.Opt(IDL.Nat),
    'attempts' : IDL.Nat,
    'srProgression' : IDL.Opt(IDL.Nat),
    'trackId' : IDL.Text,
  });
  const StoreItem = IDL.Record({
    'costInXP' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'srLevel' : IDL.Nat,
    'name' : IDL.Text,
    'skillRating' : IDL.Nat,
    'winRate' : IDL.Float64,
    'totalRaces' : IDL.Nat,
  });
  const Time = IDL.Int;
  const DirectMessage = IDL.Record({
    'content' : IDL.Text,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  const TrackPosition = IDL.Nat16;
  const Position = IDL.Record({
    'checkpoint' : IDL.Nat8,
    'position' : TrackPosition,
  });
  const F1RacingTrack = IDL.Record({
    'textureAsset' : IDL.Text,
    'pitLane' : IDL.Vec(Position),
    'checkpoints' : IDL.Vec(Position),
    'finishLine' : IDL.Vec(Position),
    'points' : IDL.Vec(Position),
  });
  const Season = IDL.Nat8;
  const LeaderboardEntry = IDL.Record({
    'player' : IDL.Principal,
    'skill' : IDL.Nat,
  });
  const StoreData = IDL.Record({
    'userXP' : IDL.Nat,
    'totalPurchased' : IDL.Nat,
    'ownedItems' : IDL.Vec(IDL.Text),
    'availableItems' : IDL.Vec(StoreItem),
  });
  const GroupView = IDL.Record({
    'owner' : IDL.Principal,
    'maxCapacity' : IDL.Nat,
    'name' : IDL.Text,
    'memberCount' : IDL.Nat,
    'trackId' : IDL.Opt(IDL.Text),
    'groupType' : GroupType,
  });
  const PlayerStats = IDL.Record({ 'totalTime' : IDL.Nat, 'races' : IDL.Nat });
  const RaceStats = IDL.Record({
    'bestTime' : IDL.Nat,
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
  });
  const Subscription = IDL.Record({
    'status' : IDL.Variant({
      'active' : IDL.Null,
      'canceled' : IDL.Null,
      'expired' : IDL.Null,
    }),
    'plan' : Plan,
    'expirationDate' : IDL.Opt(Time),
    'stripeSessionId' : IDL.Opt(IDL.Text),
    'startDate' : Time,
  });
  const LapTime = IDL.Record({ 'lap' : IDL.Nat, 'time' : IDL.Int });
  const CarState = IDL.Record({
    'isRacing' : IDL.Bool,
    'direction' : IDL.Float64,
    'velocity' : IDL.Float64,
    'laps' : IDL.Nat,
    'lapTimes' : IDL.Vec(LapTime),
    'position' : Position,
  });
  const StoreStatus = IDL.Record({
    'balance' : IDL.Nat,
    'ownedItems' : IDL.Vec(IDL.Text),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const TeamMember = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'role' : TeamRole,
  });
  const TeamRoster = IDL.Record({
    'directors' : IDL.Vec(TeamMember),
    'pitCrew' : IDL.Vec(TeamMember),
    'drivers' : IDL.Vec(TeamMember),
  });
  const Race = IDL.Record({ 'score' : IDL.Nat, 'driver' : IDL.Principal });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activatePaidPlan' : IDL.Func([Plan, IDL.Text], [], []),
    'addFriend' : IDL.Func([IDL.Principal], [], []),
    'addRace' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelSubscription' : IDL.Func([], [], []),
    'changeRole' : IDL.Func([TeamRole], [], []),
    'collectXPCoin' : IDL.Func([XPCoinType, IDL.Text], [IDL.Nat], []),
    'completeAIRace' : IDL.Func([IDL.Text, AIInput], [IDL.Nat], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createGroup' : IDL.Func(
        [IDL.Text, GroupType, IDL.Nat, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'creditXP' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'finishRace' : IDL.Func([IDL.Text], [], []),
    'getAIDrivenRaceResults' : IDL.Func([], [IDL.Opt(AIRaceResult)], ['query']),
    'getAvailablePlans' : IDL.Func([], [IDL.Vec(Plan)], ['query']),
    'getAvailableStoreItems' : IDL.Func([], [IDL.Vec(StoreItem)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversationWithPeer' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DirectMessage)],
        ['query'],
      ),
    'getCurrentPlan' : IDL.Func([], [Plan], ['query']),
    'getF1RacingTrack' : IDL.Func([], [IDL.Opt(F1RacingTrack)], ['query']),
    'getFriendsLeaderboard' : IDL.Func(
        [Season],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getFullStoreData' : IDL.Func([], [StoreData], ['query']),
    'getGlobalLeaderboard' : IDL.Func(
        [Season],
        [IDL.Opt(IDL.Vec(LeaderboardEntry))],
        ['query'],
      ),
    'getGroupMembers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getGroups' : IDL.Func([], [IDL.Vec(GroupView)], ['query']),
    'getLeaderboardFriends' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getMyFriends' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getMyOwnedItems' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getMyPlayerStats' : IDL.Func([], [IDL.Opt(PlayerStats)], ['query']),
    'getMyRaceStats' : IDL.Func([], [IDL.Opt(RaceStats)], ['query']),
    'getMySubscription' : IDL.Func([], [Subscription], ['query']),
    'getPlanExpiration' : IDL.Func([], [IDL.Opt(Time)], ['query']),
    'getPlanPricing' : IDL.Func([Plan], [IDL.Nat], ['query']),
    'getPlayerStats' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PlayerStats)],
        ['query'],
      ),
    'getRaceCarStates' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Opt(CarState)))],
        ['query'],
      ),
    'getRacePositions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Opt(Position)))],
        ['query'],
      ),
    'getRaceStats' : IDL.Func([IDL.Principal], [IDL.Opt(RaceStats)], ['query']),
    'getStoreStatus' : IDL.Func([], [StoreStatus], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTeamRoster' : IDL.Func([], [TeamRoster], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'joinGroup' : IDL.Func([IDL.Text], [], []),
    'joinMatchmaking' : IDL.Func([], [], []),
    'joinRace' : IDL.Func([IDL.Text], [], []),
    'joinTeam' : IDL.Func([IDL.Text, TeamRole], [], []),
    'leaveGroup' : IDL.Func([IDL.Text], [], []),
    'leaveTeam' : IDL.Func([], [], []),
    'progressSRByAI' : IDL.Func([IDL.Nat], [], []),
    'purchaseItem' : IDL.Func([IDL.Text], [], []),
    'registerRaceResult' : IDL.Func([Race], [], []),
    'removeFriend' : IDL.Func([IDL.Principal], [], []),
    'resetSeason' : IDL.Func([Season], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendDirectMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'setF1RacingTrack' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(Position),
          IDL.Vec(Position),
          IDL.Vec(Position),
          IDL.Vec(Position),
        ],
        [],
        [],
      ),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'setWorldRaceRecord' : IDL.Func([IDL.Text, IDL.Int], [], []),
    'startAIRace' : IDL.Func([IDL.Text, AIInput], [], []),
    'startRace' : IDL.Func([IDL.Text], [], []),
    'startTournament' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCarState' : IDL.Func(
        [Position, IDL.Float64, IDL.Float64, IDL.Nat],
        [],
        [],
      ),
    'updateCurrentSeason' : IDL.Func([IDL.Nat], [], []),
    'updateLeaderboard' : IDL.Func([Season, IDL.Vec(LeaderboardEntry)], [], []),
    'updateRaceStats' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };