/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LeaderboardEntry {
    player: Principal;
    skill: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface GroupView {
    owner: Principal;
    maxCapacity: bigint;
    name: string;
    memberCount: bigint;
    trackId?: string;
    groupType: GroupType;
}
export interface Subscription {
    status: Variant_active_canceled_expired;
    plan: Plan;
    expirationDate?: Time;
    stripeSessionId?: string;
    startDate: Time;
}
export type Season = number;
export interface AIInput {
    backward: boolean;
    forward: boolean;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface Race {
    score: bigint;
    driver: Principal;
}
export interface DirectMessage {
    content: string;
    recipient: Principal;
    sender: Principal;
    timestamp: Time;
}
export interface CarState {
    isRacing: boolean;
    direction: number;
    velocity: number;
    laps: bigint;
    lapTimes: Array<LapTime>;
    position: Position;
}
export interface StoreData {
    userXP: bigint;
    totalPurchased: bigint;
    ownedItems: Array<string>;
    availableItems: Array<StoreItem>;
}
export interface StoreStatus {
    balance: bigint;
    ownedItems: Array<string>;
}
export interface RaceStats {
    bestTime: bigint;
    wins: bigint;
    losses: bigint;
}
export interface AIRaceResult {
    completionTime?: bigint;
    bestTime?: bigint;
    attempts: bigint;
    srProgression?: bigint;
    trackId: string;
}
export type TrackPosition = number;
export interface LapTime {
    lap: bigint;
    time: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface F1RacingTrack {
    textureAsset: string;
    pitLane: Array<Position>;
    checkpoints: Array<Position>;
    finishLine: Array<Position>;
    points: Array<Position>;
}
export interface StoreItem {
    costInXP: bigint;
    name: string;
    description: string;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface Position {
    checkpoint: number;
    position: TrackPosition;
}
export interface TeamMember {
    principal: Principal;
    name: string;
    role: TeamRole;
}
export interface TeamRoster {
    directors: Array<TeamMember>;
    pitCrew: Array<TeamMember>;
    drivers: Array<TeamMember>;
}
export interface PlayerStats {
    totalTime: bigint;
    races: bigint;
}
export interface UserProfile {
    srLevel: bigint;
    name: string;
    skillRating: bigint;
    winRate: number;
    totalRaces: bigint;
}
export enum GroupType {
    race = "race",
    tournament = "tournament"
}
export enum Plan {
    free = "free",
    monthly = "monthly",
    yearly = "yearly"
}
export enum TeamRole {
    pitCrew = "pitCrew",
    director = "director",
    driver = "driver"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_active_canceled_expired {
    active = "active",
    canceled = "canceled",
    expired = "expired"
}
export enum XPCoinType {
    xp1 = "xp1",
    xp5 = "xp5",
    xp10 = "xp10",
    xp20 = "xp20"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    activatePaidPlan(plan: Plan, stripeSessionId: string): Promise<void>;
    addFriend(friend: Principal): Promise<void>;
    addRace(speed: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelSubscription(): Promise<void>;
    changeRole(role: TeamRole): Promise<void>;
    collectXPCoin(coinType: XPCoinType, trackId: string): Promise<bigint>;
    completeAIRace(trackId: string, input: AIInput): Promise<bigint>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createGroup(name: string, groupType: GroupType, maxCapacity: bigint, trackId: string | null): Promise<void>;
    creditXP(user: Principal, amount: bigint): Promise<void>;
    finishRace(trackId: string): Promise<void>;
    getAIDrivenRaceResults(): Promise<AIRaceResult | null>;
    getAvailablePlans(): Promise<Array<Plan>>;
    getAvailableStoreItems(): Promise<Array<StoreItem>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getConversationWithPeer(peer: Principal): Promise<Array<DirectMessage>>;
    getCurrentPlan(): Promise<Plan>;
    getF1RacingTrack(): Promise<F1RacingTrack | null>;
    getFriendsLeaderboard(season: Season): Promise<Array<LeaderboardEntry>>;
    getFullStoreData(): Promise<StoreData>;
    getGlobalLeaderboard(season: Season): Promise<Array<LeaderboardEntry> | null>;
    getGroupMembers(name: string): Promise<Array<Principal>>;
    getGroups(): Promise<Array<GroupView>>;
    getLeaderboardFriends(): Promise<Array<Principal>>;
    getMyFriends(): Promise<Array<Principal>>;
    getMyOwnedItems(): Promise<Array<string>>;
    getMyPlayerStats(): Promise<PlayerStats | null>;
    getMyRaceStats(): Promise<RaceStats | null>;
    getMySubscription(): Promise<Subscription>;
    getPlanExpiration(): Promise<Time | null>;
    getPlanPricing(plan: Plan): Promise<bigint>;
    getPlayerStats(player: Principal): Promise<PlayerStats | null>;
    getRaceCarStates(trackId: string): Promise<Array<[Principal, CarState | null]>>;
    getRacePositions(trackId: string): Promise<Array<[Principal, Position | null]>>;
    getRaceStats(player: Principal): Promise<RaceStats | null>;
    getStoreStatus(): Promise<StoreStatus>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTeamRoster(): Promise<TeamRoster>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    joinGroup(name: string): Promise<void>;
    joinMatchmaking(): Promise<void>;
    joinRace(trackId: string): Promise<void>;
    joinTeam(name: string, role: TeamRole): Promise<void>;
    leaveGroup(name: string): Promise<void>;
    leaveTeam(): Promise<void>;
    progressSRByAI(srIncrement: bigint): Promise<void>;
    purchaseItem(itemName: string): Promise<void>;
    registerRaceResult(raceData: Race): Promise<void>;
    removeFriend(friend: Principal): Promise<void>;
    resetSeason(season: Season): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendDirectMessage(recipient: Principal, content: string): Promise<void>;
    setF1RacingTrack(textureAsset: string, points: Array<Position>, checkpoints: Array<Position>, pitLane: Array<Position>, finishLine: Array<Position>): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    setWorldRaceRecord(trackId: string, lapTime: bigint): Promise<void>;
    startAIRace(trackId: string, input: AIInput): Promise<void>;
    startRace(trackId: string): Promise<void>;
    startTournament(trackId: string): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateCarState(position: Position, velocity: number, direction: number, laps: bigint): Promise<void>;
    updateCurrentSeason(raceCount: bigint): Promise<void>;
    updateLeaderboard(season: Season, entries: Array<LeaderboardEntry>): Promise<void>;
    updateRaceStats(wins: bigint, losses: bigint, bestTime: bigint): Promise<void>;
}
import type { AIRaceResult as _AIRaceResult, CarState as _CarState, F1RacingTrack as _F1RacingTrack, GroupType as _GroupType, GroupView as _GroupView, LeaderboardEntry as _LeaderboardEntry, Plan as _Plan, PlayerStats as _PlayerStats, Position as _Position, RaceStats as _RaceStats, StripeSessionStatus as _StripeSessionStatus, Subscription as _Subscription, TeamMember as _TeamMember, TeamRole as _TeamRole, TeamRoster as _TeamRoster, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, XPCoinType as _XPCoinType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async activatePaidPlan(arg0: Plan, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.activatePaidPlan(to_candid_Plan_n1(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activatePaidPlan(to_candid_Plan_n1(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async addFriend(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFriend(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFriend(arg0);
            return result;
        }
    }
    async addRace(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRace(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRace(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelSubscription(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelSubscription();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelSubscription();
            return result;
        }
    }
    async changeRole(arg0: TeamRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.changeRole(to_candid_TeamRole_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeRole(to_candid_TeamRole_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async collectXPCoin(arg0: XPCoinType, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.collectXPCoin(to_candid_XPCoinType_n7(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.collectXPCoin(to_candid_XPCoinType_n7(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async completeAIRace(arg0: string, arg1: AIInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.completeAIRace(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeAIRace(arg0, arg1);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createGroup(arg0: string, arg1: GroupType, arg2: bigint, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createGroup(arg0, to_candid_GroupType_n9(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGroup(arg0, to_candid_GroupType_n9(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async creditXP(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.creditXP(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.creditXP(arg0, arg1);
            return result;
        }
    }
    async finishRace(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.finishRace(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.finishRace(arg0);
            return result;
        }
    }
    async getAIDrivenRaceResults(): Promise<AIRaceResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAIDrivenRaceResults();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAIDrivenRaceResults();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailablePlans(): Promise<Array<Plan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailablePlans();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailablePlans();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableStoreItems(): Promise<Array<StoreItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableStoreItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableStoreItems();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversationWithPeer(arg0: Principal): Promise<Array<DirectMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversationWithPeer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversationWithPeer(arg0);
            return result;
        }
    }
    async getCurrentPlan(): Promise<Plan> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentPlan();
                return from_candid_Plan_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentPlan();
            return from_candid_Plan_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getF1RacingTrack(): Promise<F1RacingTrack | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getF1RacingTrack();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getF1RacingTrack();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFriendsLeaderboard(arg0: Season): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriendsLeaderboard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriendsLeaderboard(arg0);
            return result;
        }
    }
    async getFullStoreData(): Promise<StoreData> {
        if (this.processError) {
            try {
                const result = await this.actor.getFullStoreData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFullStoreData();
            return result;
        }
    }
    async getGlobalLeaderboard(arg0: Season): Promise<Array<LeaderboardEntry> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlobalLeaderboard(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlobalLeaderboard(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGroupMembers(arg0: string): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroupMembers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroupMembers(arg0);
            return result;
        }
    }
    async getGroups(): Promise<Array<GroupView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroups();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroups();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboardFriends(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboardFriends();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboardFriends();
            return result;
        }
    }
    async getMyFriends(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyFriends();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyFriends();
            return result;
        }
    }
    async getMyOwnedItems(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOwnedItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOwnedItems();
            return result;
        }
    }
    async getMyPlayerStats(): Promise<PlayerStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPlayerStats();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPlayerStats();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRaceStats(): Promise<RaceStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRaceStats();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRaceStats();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMySubscription(): Promise<Subscription> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySubscription();
                return from_candid_Subscription_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySubscription();
            return from_candid_Subscription_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlanExpiration(): Promise<Time | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlanExpiration();
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlanExpiration();
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlanPricing(arg0: Plan): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlanPricing(to_candid_Plan_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlanPricing(to_candid_Plan_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getPlayerStats(arg0: Principal): Promise<PlayerStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerStats(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerStats(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRaceCarStates(arg0: string): Promise<Array<[Principal, CarState | null]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRaceCarStates(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRaceCarStates(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRacePositions(arg0: string): Promise<Array<[Principal, Position | null]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRacePositions(arg0);
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRacePositions(arg0);
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRaceStats(arg0: Principal): Promise<RaceStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRaceStats(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRaceStats(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStoreStatus(): Promise<StoreStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoreStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoreStatus();
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeamRoster(): Promise<TeamRoster> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamRoster();
                return from_candid_TeamRoster_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamRoster();
            return from_candid_TeamRoster_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async joinGroup(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinGroup(arg0);
            return result;
        }
    }
    async joinMatchmaking(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinMatchmaking();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinMatchmaking();
            return result;
        }
    }
    async joinRace(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinRace(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinRace(arg0);
            return result;
        }
    }
    async joinTeam(arg0: string, arg1: TeamRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinTeam(arg0, to_candid_TeamRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinTeam(arg0, to_candid_TeamRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async leaveGroup(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveGroup(arg0);
            return result;
        }
    }
    async leaveTeam(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveTeam();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveTeam();
            return result;
        }
    }
    async progressSRByAI(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.progressSRByAI(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.progressSRByAI(arg0);
            return result;
        }
    }
    async purchaseItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.purchaseItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchaseItem(arg0);
            return result;
        }
    }
    async registerRaceResult(arg0: Race): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerRaceResult(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerRaceResult(arg0);
            return result;
        }
    }
    async removeFriend(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFriend(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFriend(arg0);
            return result;
        }
    }
    async resetSeason(arg0: Season): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetSeason(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetSeason(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async sendDirectMessage(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendDirectMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendDirectMessage(arg0, arg1);
            return result;
        }
    }
    async setF1RacingTrack(arg0: string, arg1: Array<Position>, arg2: Array<Position>, arg3: Array<Position>, arg4: Array<Position>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setF1RacingTrack(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setF1RacingTrack(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async setWorldRaceRecord(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setWorldRaceRecord(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setWorldRaceRecord(arg0, arg1);
            return result;
        }
    }
    async startAIRace(arg0: string, arg1: AIInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startAIRace(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startAIRace(arg0, arg1);
            return result;
        }
    }
    async startRace(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startRace(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startRace(arg0);
            return result;
        }
    }
    async startTournament(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startTournament(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startTournament(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateCarState(arg0: Position, arg1: number, arg2: number, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCarState(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCarState(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateCurrentSeason(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCurrentSeason(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCurrentSeason(arg0);
            return result;
        }
    }
    async updateLeaderboard(arg0: Season, arg1: Array<LeaderboardEntry>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLeaderboard(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLeaderboard(arg0, arg1);
            return result;
        }
    }
    async updateRaceStats(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRaceStats(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRaceStats(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_AIRaceResult_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AIRaceResult): AIRaceResult {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_GroupType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GroupType): GroupType {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_GroupView_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GroupView): GroupView {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Plan_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Plan): Plan {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_Subscription_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subscription): Subscription {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_TeamMember_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeamMember): TeamMember {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_TeamRole_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeamRole): TeamRole {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_TeamRoster_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeamRoster): TeamRoster {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AIRaceResult]): AIRaceResult | null {
    return value.length === 0 ? null : from_candid_AIRaceResult_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_F1RacingTrack]): F1RacingTrack | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_LeaderboardEntry>]): Array<LeaderboardEntry> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerStats]): PlayerStats | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RaceStats]): RaceStats | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CarState]): CarState | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Position]): Position | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completionTime: [] | [bigint];
    bestTime: [] | [bigint];
    attempts: bigint;
    srProgression: [] | [bigint];
    trackId: string;
}): {
    completionTime?: bigint;
    bestTime?: bigint;
    attempts: bigint;
    srProgression?: bigint;
    trackId: string;
} {
    return {
        completionTime: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.completionTime)),
        bestTime: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.bestTime)),
        attempts: value.attempts,
        srProgression: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.srProgression)),
        trackId: value.trackId
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    owner: Principal;
    maxCapacity: bigint;
    name: string;
    memberCount: bigint;
    trackId: [] | [string];
    groupType: _GroupType;
}): {
    owner: Principal;
    maxCapacity: bigint;
    name: string;
    memberCount: bigint;
    trackId?: string;
    groupType: GroupType;
} {
    return {
        owner: value.owner,
        maxCapacity: value.maxCapacity,
        name: value.name,
        memberCount: value.memberCount,
        trackId: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.trackId)),
        groupType: from_candid_GroupType_n28(_uploadFile, _downloadFile, value.groupType)
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        active: null;
    } | {
        canceled: null;
    } | {
        expired: null;
    };
    plan: _Plan;
    expirationDate: [] | [_Time];
    stripeSessionId: [] | [string];
    startDate: _Time;
}): {
    status: Variant_active_canceled_expired;
    plan: Plan;
    expirationDate?: Time;
    stripeSessionId?: string;
    startDate: Time;
} {
    return {
        status: from_candid_variant_n34(_uploadFile, _downloadFile, value.status),
        plan: from_candid_Plan_n17(_uploadFile, _downloadFile, value.plan),
        expirationDate: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.expirationDate)),
        stripeSessionId: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.stripeSessionId)),
        startDate: value.startDate
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    directors: Array<_TeamMember>;
    pitCrew: Array<_TeamMember>;
    drivers: Array<_TeamMember>;
}): {
    directors: Array<TeamMember>;
    pitCrew: Array<TeamMember>;
    drivers: Array<TeamMember>;
} {
    return {
        directors: from_candid_vec_n47(_uploadFile, _downloadFile, value.directors),
        pitCrew: from_candid_vec_n47(_uploadFile, _downloadFile, value.pitCrew),
        drivers: from_candid_vec_n47(_uploadFile, _downloadFile, value.drivers)
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    name: string;
    role: _TeamRole;
}): {
    principal: Principal;
    name: string;
    role: TeamRole;
} {
    return {
        principal: value.principal,
        name: value.name,
        role: from_candid_TeamRole_n50(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_tuple_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, [] | [_CarState]]): [Principal, CarState | null] {
    return [
        value[0],
        from_candid_opt_n38(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, [] | [_Position]]): [Principal, Position | null] {
    return [
        value[0],
        from_candid_opt_n41(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    free: null;
} | {
    monthly: null;
} | {
    yearly: null;
}): Plan {
    return "free" in value ? Plan.free : "monthly" in value ? Plan.monthly : "yearly" in value ? Plan.yearly : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    race: null;
} | {
    tournament: null;
}): GroupType {
    return "race" in value ? GroupType.race : "tournament" in value ? GroupType.tournament : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    canceled: null;
} | {
    expired: null;
}): Variant_active_canceled_expired {
    return "active" in value ? Variant_active_canceled_expired.active : "canceled" in value ? Variant_active_canceled_expired.canceled : "expired" in value ? Variant_active_canceled_expired.expired : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n44(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pitCrew: null;
} | {
    director: null;
} | {
    driver: null;
}): TeamRole {
    return "pitCrew" in value ? TeamRole.pitCrew : "director" in value ? TeamRole.director : "driver" in value ? TeamRole.driver : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Plan>): Array<Plan> {
    return value.map((x)=>from_candid_Plan_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GroupView>): Array<GroupView> {
    return value.map((x)=>from_candid_GroupView_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, [] | [_CarState]]>): Array<[Principal, CarState | null]> {
    return value.map((x)=>from_candid_tuple_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, [] | [_Position]]>): Array<[Principal, Position | null]> {
    return value.map((x)=>from_candid_tuple_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TeamMember>): Array<TeamMember> {
    return value.map((x)=>from_candid_TeamMember_n48(_uploadFile, _downloadFile, x));
}
function to_candid_GroupType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GroupType): _GroupType {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Plan_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Plan): _Plan {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_TeamRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TeamRole): _TeamRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_XPCoinType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: XPCoinType): _XPCoinType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GroupType): {
    race: null;
} | {
    tournament: null;
} {
    return value == GroupType.race ? {
        race: null
    } : value == GroupType.tournament ? {
        tournament: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Plan): {
    free: null;
} | {
    monthly: null;
} | {
    yearly: null;
} {
    return value == Plan.free ? {
        free: null
    } : value == Plan.monthly ? {
        monthly: null
    } : value == Plan.yearly ? {
        yearly: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TeamRole): {
    pitCrew: null;
} | {
    director: null;
} | {
    driver: null;
} {
    return value == TeamRole.pitCrew ? {
        pitCrew: null
    } : value == TeamRole.director ? {
        director: null
    } : value == TeamRole.driver ? {
        driver: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: XPCoinType): {
    xp1: null;
} | {
    xp5: null;
} | {
    xp10: null;
} | {
    xp20: null;
} {
    return value == XPCoinType.xp1 ? {
        xp1: null
    } : value == XPCoinType.xp5 ? {
        xp5: null
    } : value == XPCoinType.xp10 ? {
        xp10: null
    } : value == XPCoinType.xp20 ? {
        xp20: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
