/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIInput { 'backward' : boolean, 'forward' : boolean }
export interface AIRaceResult {
  'completionTime' : [] | [bigint],
  'bestTime' : [] | [bigint],
  'attempts' : bigint,
  'srProgression' : [] | [bigint],
  'trackId' : string,
}
export interface CarState {
  'isRacing' : boolean,
  'direction' : number,
  'velocity' : number,
  'laps' : bigint,
  'lapTimes' : Array<LapTime>,
  'position' : Position,
}
export interface DirectMessage {
  'content' : string,
  'recipient' : Principal,
  'sender' : Principal,
  'timestamp' : Time,
}
export interface F1RacingTrack {
  'textureAsset' : string,
  'pitLane' : Array<Position>,
  'checkpoints' : Array<Position>,
  'finishLine' : Array<Position>,
  'points' : Array<Position>,
}
export type GroupType = { 'race' : null } |
  { 'tournament' : null };
export interface GroupView {
  'owner' : Principal,
  'maxCapacity' : bigint,
  'name' : string,
  'memberCount' : bigint,
  'trackId' : [] | [string],
  'groupType' : GroupType,
}
export interface LapTime { 'lap' : bigint, 'time' : bigint }
export interface LeaderboardEntry { 'player' : Principal, 'skill' : bigint }
export type Plan = { 'free' : null } |
  { 'monthly' : null } |
  { 'yearly' : null };
export interface PlayerStats { 'totalTime' : bigint, 'races' : bigint }
export interface Position { 'checkpoint' : number, 'position' : TrackPosition }
export interface Race { 'score' : bigint, 'driver' : Principal }
export interface RaceStats {
  'bestTime' : bigint,
  'wins' : bigint,
  'losses' : bigint,
}
export type Season = number;
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StoreData {
  'userXP' : bigint,
  'totalPurchased' : bigint,
  'ownedItems' : Array<string>,
  'availableItems' : Array<StoreItem>,
}
export interface StoreItem {
  'costInXP' : bigint,
  'name' : string,
  'description' : string,
}
export interface StoreStatus {
  'balance' : bigint,
  'ownedItems' : Array<string>,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Subscription {
  'status' : { 'active' : null } |
    { 'canceled' : null } |
    { 'expired' : null },
  'plan' : Plan,
  'expirationDate' : [] | [Time],
  'stripeSessionId' : [] | [string],
  'startDate' : Time,
}
export interface TeamMember {
  'principal' : Principal,
  'name' : string,
  'role' : TeamRole,
}
export type TeamRole = { 'pitCrew' : null } |
  { 'director' : null } |
  { 'driver' : null };
export interface TeamRoster {
  'directors' : Array<TeamMember>,
  'pitCrew' : Array<TeamMember>,
  'drivers' : Array<TeamMember>,
}
export type Time = bigint;
export type TrackPosition = number;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'srLevel' : bigint,
  'name' : string,
  'skillRating' : bigint,
  'winRate' : number,
  'totalRaces' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type XPCoinType = { 'xp1' : null } |
  { 'xp5' : null } |
  { 'xp10' : null } |
  { 'xp20' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'activatePaidPlan' : ActorMethod<[Plan, string], undefined>,
  'addFriend' : ActorMethod<[Principal], undefined>,
  'addRace' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelSubscription' : ActorMethod<[], undefined>,
  'changeRole' : ActorMethod<[TeamRole], undefined>,
  'collectXPCoin' : ActorMethod<[XPCoinType, string], bigint>,
  'completeAIRace' : ActorMethod<[string, AIInput], bigint>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createGroup' : ActorMethod<
    [string, GroupType, bigint, [] | [string]],
    undefined
  >,
  'creditXP' : ActorMethod<[Principal, bigint], undefined>,
  'finishRace' : ActorMethod<[string], undefined>,
  'getAIDrivenRaceResults' : ActorMethod<[], [] | [AIRaceResult]>,
  'getAvailablePlans' : ActorMethod<[], Array<Plan>>,
  'getAvailableStoreItems' : ActorMethod<[], Array<StoreItem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversationWithPeer' : ActorMethod<[Principal], Array<DirectMessage>>,
  'getCurrentPlan' : ActorMethod<[], Plan>,
  'getF1RacingTrack' : ActorMethod<[], [] | [F1RacingTrack]>,
  'getFriendsLeaderboard' : ActorMethod<[Season], Array<LeaderboardEntry>>,
  'getFullStoreData' : ActorMethod<[], StoreData>,
  'getGlobalLeaderboard' : ActorMethod<
    [Season],
    [] | [Array<LeaderboardEntry>]
  >,
  'getGroupMembers' : ActorMethod<[string], Array<Principal>>,
  'getGroups' : ActorMethod<[], Array<GroupView>>,
  'getLeaderboardFriends' : ActorMethod<[], Array<Principal>>,
  'getMyFriends' : ActorMethod<[], Array<Principal>>,
  'getMyOwnedItems' : ActorMethod<[], Array<string>>,
  'getMyPlayerStats' : ActorMethod<[], [] | [PlayerStats]>,
  'getMyRaceStats' : ActorMethod<[], [] | [RaceStats]>,
  'getMySubscription' : ActorMethod<[], Subscription>,
  'getPlanExpiration' : ActorMethod<[], [] | [Time]>,
  'getPlanPricing' : ActorMethod<[Plan], bigint>,
  'getPlayerStats' : ActorMethod<[Principal], [] | [PlayerStats]>,
  'getRaceCarStates' : ActorMethod<
    [string],
    Array<[Principal, [] | [CarState]]>
  >,
  'getRacePositions' : ActorMethod<
    [string],
    Array<[Principal, [] | [Position]]>
  >,
  'getRaceStats' : ActorMethod<[Principal], [] | [RaceStats]>,
  'getStoreStatus' : ActorMethod<[], StoreStatus>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTeamRoster' : ActorMethod<[], TeamRoster>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'joinGroup' : ActorMethod<[string], undefined>,
  'joinMatchmaking' : ActorMethod<[], undefined>,
  'joinRace' : ActorMethod<[string], undefined>,
  'joinTeam' : ActorMethod<[string, TeamRole], undefined>,
  'leaveGroup' : ActorMethod<[string], undefined>,
  'leaveTeam' : ActorMethod<[], undefined>,
  'progressSRByAI' : ActorMethod<[bigint], undefined>,
  'purchaseItem' : ActorMethod<[string], undefined>,
  'registerRaceResult' : ActorMethod<[Race], undefined>,
  'removeFriend' : ActorMethod<[Principal], undefined>,
  'resetSeason' : ActorMethod<[Season], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendDirectMessage' : ActorMethod<[Principal, string], undefined>,
  'setF1RacingTrack' : ActorMethod<
    [
      string,
      Array<Position>,
      Array<Position>,
      Array<Position>,
      Array<Position>,
    ],
    undefined
  >,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setWorldRaceRecord' : ActorMethod<[string, bigint], undefined>,
  'startAIRace' : ActorMethod<[string, AIInput], undefined>,
  'startRace' : ActorMethod<[string], undefined>,
  'startTournament' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCarState' : ActorMethod<[Position, number, number, bigint], undefined>,
  'updateCurrentSeason' : ActorMethod<[bigint], undefined>,
  'updateLeaderboard' : ActorMethod<
    [Season, Array<LeaderboardEntry>],
    undefined
  >,
  'updateRaceStats' : ActorMethod<[bigint, bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];